### ISSUE TITLE
Bug with locating player in some rooms and request for Windows compatibility

### ISSUE THREAD

**Issue by vincentwen1995** [0xSeanll/LatiaoAid#4]
Hi, thank you for your work! During running the script, I noticed some peculiar cases where the script could not locate the player and triggers the traceback:
```
(latiao) E:\latiao\LatiaoAid>python console_run.py -r 594004 -l --log-path E:\latiao\log.txt --driver-path E:\latiao\geckodriver.exe
[2020-06-20 18:44:28.112436] 【】Firefox Launched (゜-゜)つロ
[2020-06-20 18:44:34.396850] 【MAIN】等待亲爱的B站用户登陆～！ (゜-゜)つロ
[2020-06-20 18:44:48.993572] 【MAIN】恭喜你这个B站用户，登陆成功啦～！ (゜-゜)つロ
[2020-06-20 18:44:48.997570] 【MAIN】开始加载 Base Tab (゜-゜)つロ
Traceback (most recent call last):
  File "console_run.py", line 155, in <module>
    exit_timer(args.second + args.minute * 60)(run_LatiaoAid_main)(args)
  File "console_run.py", line 99, in run_LatiaoAid_main
    log_path=args.log_path,
  File "E:\latiao\LatiaoAid\LatiaoAid.py", line 277, in main
    self.load_base_tab()
  File "E:\latiao\LatiaoAid\LatiaoAid.py", line 66, in load_base_tab
    ec.presence_of_element_located((By.XPATH, '//div[@class="bilibili-live-player relative"]')))
  File "H:\Anaconda3\envs\latiao\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```
The specific live room where I met this problem looked like this 
![微信截图_20200620190535](https://user-images.githubusercontent.com/29601049/85207576-ed085a00-b329-11ea-8816-dad129212894.png)

Furthermore, when I tried out the timer functionality, I have also noticed the problem that the `signal.alarm()` method is not available on Windows platform with `signal.SIGALRM`. As I looked into it, I found some discussions about a Windows equivalent of `signal.SIGALRM` [here](https://stackoverflow.com/questions/8420422/python-windows-equivalent-of-sigalrm), which might be useful.

**Comment by 0xSeanll** [comment]
Hi, @vincentwen1995 . Thanks for your report.

That live room is different from others, since it enclosed the normal live room in an iframe tag. So, our program was unable to reach the target element (in this case, the live player) in the given time, thus an exception was thrown. We are definitely going to fix this.

As for the second issue, one of our contributors (though there's only two) will work on it. :)

**Comment by loopyme** [comment]
We probably do not really need the exit_timer and the signal stuffs, merge the functionality into LatiaoAid might do the trick

Working on it now, patch will come out soon

**Comment by 0xSeanll** [comment]
Hi, @vincentwen1995 .
In your case, live room 528 is chosen to be the base tab and there seems to be an event in that live room, so our script is unable to work. We recommend you choose a less popular live room so that there is unlikely to have any events. The code has been updated, so you can configure that in `run.py` or `console_run.py` with `room` option. You need to specify the room number, or the default will be used.

**Comment by vincentwen1995** [comment]
> Hi, @vincentwen1995 .
> In your case, live room 528 is chosen to be the base tab and there seems to be an event in that live room, so our script is unable to work. We recommend you choose a less popular live room so that there is unlikely to have any events. The code has been updated, so you can configure that in `run.py` or `console_run.py` with `room` option. You need to specify the room number, or the default will be used.

Thank you for the response! I did specify another room with normal condition and the script have been running smooth ever since.
